### DISCUSSION TITLE
Flex 布局

### DISCUSSION THREAD

**Discussion by huxinfeng** [huxinfeng/huxinfeng.github.io#20] [CSS]
## 1. 概念

采用 Flex 布局的元素，称为 Flex 容器（flex container），简称"容器"。它的所有子元素自动成为容器成员，称为 Flex 项目（flex item），简称"项目"。

![image](https://github.com/user-attachments/assets/5e1ccd32-9772-43bd-a026-e1dd44f969bc)

容器默认存在两根轴：水平的主轴（main axis）和垂直的交叉轴（cross axis）。主轴的开始位置（与边框的交叉点）叫做 `main start`，结束位置叫做 `main end`；交叉轴的开始位置叫做 `cross start`，结束位置叫做 `cross end`。

项目默认沿主轴排列。单个项目占据的主轴空间叫做 `main size`，占据的交叉轴空间叫做 `cross size`。

## 2. 容器的属性

以下 6 个属性设置在容器上

1. flex-direction
2. flex-wrap
3. flex-flow
4. justify-content
5. align-items
6. align-content

### 2.1 flex-direction 属性

flex-direction 属性决定主轴的方向（即项目的排列方向）。

![image](https://github.com/user-attachments/assets/ebc7f341-510d-43d7-a522-aa37e2020bb0)

```css
.box {
  flex-direction: row | row-reverse | column | column-reverse;
}
```

它有 4 个值

- row（默认值）：主轴为水平方向，起点在左端
- row-reverse：主轴为水平方向，起点在右端
- column：主轴为垂直方向，起点在上沿
- column-reverse：主轴为垂直方向，起点在下沿

### 2.2 flex-wrap 属性

默认情况下，项目都排在一条线（又称"轴线"）上。flex-wrap 属性定义，如果一条轴线排不下，如何换行。

![image](https://github.com/user-attachments/assets/c68398a7-8606-4c87-a779-8a8a6cf1b4be)

```css
.box {
  flex-wrap: nowrap | wrap | wrap-reverse;
}
```

它有 3 个值

- nowrap（默认）：不换行。
  ![image](https://github.com/user-attachments/assets/940e3dae-579c-4fbb-a0d8-439e7263c5bb)
- wrap：换行，第一行在上方。
  ![image](https://github.com/user-attachments/assets/7064e8d5-4b63-45ec-ad92-394220e59e9e)
- wrap-reverse：换行，第一行在下方。
  ![image](https://github.com/user-attachments/assets/98dfa891-15c6-47d4-982a-f9ae9eac8b47)

### 2.3 flex-flow 属性

flex-flow 属性是 flex-direction 属性和 flex-wrap 属性的简写形式，默认值为 row nowrap。

```css
.box {
  flex-flow: <flex-direction> || <flex-wrap>;
}
```

### 2.4 justify-content 属性

justify-content 属性定义了项目在主轴上的对齐方式。

![image](https://github.com/user-attachments/assets/6260810d-1f45-4481-8599-51f316bfa9d0)

```css
.box {
  justify-content: flex-start | flex-end | center | space-between | space-around;
}
```

它有 5 个值，具体对齐方式与轴的方向有关。下面假设主轴为从左到右。

- flex-start（默认值）：左对齐
- flex-end：右对齐
- center： 居中
- space-between：两端对齐，项目之间的间隔都相等
- space-around：每个项目两侧的间隔相等。所以，项目之间的间隔比项目与边框的间隔大一倍

### 2.5 align-items 属性

align-items 属性定义项目在交叉轴上如何对齐。

![image](https://github.com/user-attachments/assets/851ae757-ee46-4d17-a84b-38a1e73552a5)

```css
.box {
  align-items: flex-start | flex-end | center | baseline | stretch;
}
```

它有 5 个值。具体的对齐方式与交叉轴的方向有关，下面假设交叉轴从上到下。

- flex-start：交叉轴的起点对齐
- flex-end：交叉轴的终点对齐
- center：交叉轴的中点对齐
- baseline: 项目的第一行文字的基线对齐
- stretch（默认值）：如果项目未设置高度或设为 auto，将占满整个容器的高度

### 2.6 align-content 属性

align-content 属性定义了多根轴线的对齐方式。如果项目只有一根轴线，该属性不起作用。

![image](https://github.com/user-attachments/assets/261be645-9e12-4ee4-97af-03cf20dd5757)

```css
.box {
  align-content: flex-start | flex-end | center | space-between | space-around | stretch;
}
```

该属性有 6 个值。

- flex-start：与交叉轴的起点对齐
- flex-end：与交叉轴的终点对齐
- center：与交叉轴的中点对齐
- space-between：与交叉轴两端对齐，轴线之间的间隔平均分布
- space-around：每根轴线两侧的间隔都相等。所以，轴线之间的间隔比轴线与边框的间隔大一倍
- stretch（默认值）：轴线占满整个交叉轴

## 3. 项目的属性

以下 6 个属性设置在项目上。

1. order
2. flex-grow
3. flex-shrink
4. flex-basis
5. flex
6. align-self

### 3.1 order 属性

order 属性定义项目的排列顺序。数值越小，排列越靠前，默认为 0。

![image](https://github.com/user-attachments/assets/9b018c84-b2ef-4fa3-bf0d-5431af85a6a8)

```css
.item {
  order: <integer>;
}
```

### 3.2 flex-grow 属性

flex-grow 属性定义项目的放大比例，默认为 0，即如果存在剩余空间，也不放大。

![image](https://github.com/user-attachments/assets/fd838a70-eab3-446f-9120-625c732de383)

```css
.item {
  flex-grow: <number>; /* default 0 */
}
```

如果所有项目的 flex-grow 属性都为 1，则它们将等分剩余空间（如果有的话）。如果一个项目的 flex-grow 属性为 2，其他项目都为 1，则前者占据的剩余空间将比其他项多一倍。

### 3.3 flex-shrink 属性

flex-shrink 属性定义了项目的缩小比例，默认为 1，即如果空间不足，该项目将缩小。

![image](https://github.com/user-attachments/assets/91797051-9fd9-4f2d-bbc9-e31575c937ea)

```css
.item {
  flex-shrink: <number>; /* default 1 */
}
```

如果所有项目的 flex-shrink 属性都为 1，当空间不足时，都将等比例缩小。如果一个项目的 flex-shrink 属性为 0，其他项目都为 1，则空间不足时，前者不缩小。

负值对该属性无效。

### 3.4 flex-basis 属性

flex-basis 属性定义了在分配多余空间之前，项目占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为 auto，即项目的本来大小。

```css
.item {
  flex-basis: <length> | auto; /* default auto */
}
```

它可以设为跟 width 或 height 属性一样的值（比如 350px），则项目将占据固定空间。

### 3.5 flex 属性

flex 属性是 flex-grow, flex-shrink 和 flex-basis 的简写，默认值为 0 1 auto。后两个属性可选。

```css
.item {
  flex: none | [ < 'flex-grow' > < 'flex-shrink' >? || < 'flex-basis' > ];
}
```

该属性有两个快捷值：auto (1 1 auto) 和 none (0 0 auto)。

建议优先使用这个属性，而不是单独写三个分离的属性，因为浏览器会推算相关值。

### 3.6 align-self 属性

align-self 属性允许单个项目有与其他项目不一样的对齐方式，可覆盖 align-items 属性。默认值为 auto，表示继承父元素的 align-items 属性，如果没有父元素，则等同于 stretch。

![image](https://github.com/user-attachments/assets/e2274689-1cb2-4696-bede-7f3d068a79df)

```css
.item {
  align-self: auto | flex-start | flex-end | center | baseline | stretch;
}
```

该属性有 6 个值，除了 auto，其他都与 align-items 属性完全一致。
